### ISSUE TITLE
Padrões de GOFS Comportamentais

### ISSUE THREAD

**Issue by luisgfmarques** [UnBArqDsw2021-2/2021.2_G7_PartyRent#49]
## Descrição
Redigir documento de GOFS comportamentais com Documentos específicos para Strategy e Template Method

## Tasks
- [x] Documento de Strategy
- [x] Documento de Template Method
- [x] Apresentação do Problema
- [x] Apresentar em nível de modelagem
- [x] Apresentar em nível de código
- [x] Versionamento é rastreabilidade dos documentos
- [x] Documentos corretamente anexados na wiki do projeto.
