### ISSUE TITLE
Criação de tela de Login é registro

### ISSUE THREAD

**Issue by luisgfmarques** [UnBArqDsw2021-2/2021.2_G7_PartyRent#60]
## Descrição
Criação das telas de login e registro no front-end

## Tasks
-  [x] Tela seguindo os padrões de designe do projeto
- [x] O projeto está funcionando
- [x] As novas telas foram testadas?
